package main

import (
	"crypto/des"
	"crypto/rand"
	"fmt"
	"io"
)

func main() {
	// Create a slice to hold the DES key
	key := make([]byte, 8)

	// Read random bytes into the key slice
	_, err := io.ReadFull(rand.Reader, key)
	if err != nil {
		fmt.Println("Error generating random key:", err)
		return
	}

	// Create a DES key using the generated bytes
	desKey, err := des.NewCipher(key)
	if err != nil {
		fmt.Println("Error creating DES key:", err)
		return
	}

	// Print the generated DES key as a hexadecimal string
	fmt.Printf("Generated DES Key: %x\n", key)
}
